apiVersion: v1
kind: Service
metadata:
  name: presto
spec:
  type: NodePort
  ports:
    - name: client
      port: 8080
      nodePort: 32766
  selector:
    app: presto
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: presto
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: presto
    spec:
      containers:
        - name: presto
          image: nikkatalnikov/docker-presto:300
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
